"""Initial migration

Revision ID: 7e7c5ef4990d
Revises: f60f04c5b045
Create Date: 2023-08-03 16:54:26.461390

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7e7c5ef4990d'
down_revision = 'f60f04c5b045'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.drop_column('category_id')

    with op.batch_alter_table('store_category', schema=None) as batch_op:
        batch_op.drop_constraint('store_category_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'category', ['category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store_category', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('store_category_ibfk_1', 'category', ['category_id'], ['category_id'])

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', mysql.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_column('id')

    # ### end Alembic commands ###
